spring.application.name=pedidos

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=72dde4e7-7587-40ef-a928-4bf8f86013cb
spring.cloud.azure.active-directory.app-id-uri=api://72dde4e7-7587-40ef-a928-4bf8f86013cb
