spring.application.name=bff


spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.active-directory.app-id-uri=${AZURE_APP_ID_URI}

server.port=8080